Change some variable names

diff --git a/epub-merge b/epub-merge
--- a/epub-merge
+++ b/epub-merge
@@ -70,7 +70,7 @@ readonly ICONV_HAS_UTF_8_MAC
 # then readonly
 
 # Sorted file paths to merge to single volume ePUB
-ePUB_FILES=() 
+EPUB_FILES=() 
 
 # OPF file paths to merge
 OPF_FILES=()
@@ -98,13 +98,13 @@ TOC_VOLUME_SUFFIX=""
 TOC_VOLUME_LABELS_GIVEN=""
 
 # Custom output filename (without extension)
-ePUB_NAME="" 
+EPUB_NAME="" 
 
 # Custom output title
-ePUB_TITLE=""
+EPUB_TITLE=""
 
 # Language code (ko, en, ja, zh, ru, etc.)
-ePUB_LANG=""
+EPUB_LANG=""
 
 # Disable natural sorting of input files
 DO_NOT_SORT_PARAMS=""
@@ -175,9 +175,9 @@ debug_var() {
 parse_opts() {
 	while getopts "n:t:l:s:p:Oqx" opt; do
 		case "$opt" in
-			n) ePUB_NAME="$OPTARG" ;;             # filename
-			t) ePUB_TITLE="$OPTARG" ;;            # title
-			l) ePUB_LANG="$OPTARG" ;;             # lang
+			n) EPUB_NAME="$OPTARG" ;;             # filename
+			t) EPUB_TITLE="$OPTARG" ;;            # title
+			l) EPUB_LANG="$OPTARG" ;;             # lang
 			p) TOC_VOLUME_PREFIX="$OPTARG"; \
 				TOC_VOLUME_LABELS_GIVEN=1 ;;  # volume prefix
 			s) TOC_VOLUME_SUFFIX="$OPTARG";
@@ -194,8 +194,8 @@ parse_opts() {
 	readonly EXTRACT_MODE
 
 	if [ -n "$DEBUG" ]; then
-		debug "ePUB_NAME=$ePUB_NAME"
-		debug "ePUB_LANG=$ePUB_LANG"
+		debug "EPUB_NAME=$EPUB_NAME"
+		debug "EPUB_LANG=$EPUB_LANG"
 		debug "TOC_VOLUME_PREFIX=$TOC_VOLUME_PREFIX"
 		debug "TOC_VOLUME_SUFFIX=$TOC_VOLUME_SUFFIX"
 		debug "DO_NOT_SORT_PARAMS=$DO_NOT_SORT_PARAMS"
@@ -307,59 +307,59 @@ get_common_prefix() {
 	echo "$common" | sed -e 's/[-_[( ]*$//' -e 's/ [0-9][0-9]*$//'
 }
 
-# Determine output epub filename and title from common prefix and $ePUB_NAME
+# Determine output epub filename and title from common prefix and $EPUB_NAME
 #
 # Args: filename 1, filename 2
-# Ref: $ePUB_NAME, $ePUB_NAME, file
-# Set: $ePUB_NAME, $ePUB_NAME
+# Ref: $EPUB_NAME, $EPUB_NAME, file
+# Set: $EPUB_NAME, $EPUB_NAME
 generate_filename_and_title() {
-	if [[ -z "$ePUB_NAME" ]]; then
+	if [[ -z "$EPUB_NAME" ]]; then
 		base1="$(basename "$1")"
 		base2="$(basename "$2")"
-		ePUB_NAME="$(get_common_prefix "$base1" "$base2")"
+		EPUB_NAME="$(get_common_prefix "$base1" "$base2")"
 	fi
 
-	if [[ -z "$ePUB_NAME" ]]; then
+	if [[ -z "$EPUB_NAME" ]]; then
 		error_message="Cannot determine output name from '$1' and '$2'."
 		error_message+=$'\n'
 		error_message+="Please give \`-n' option"
 		error "$error_message"
 	fi
 
-	if [[ -f "$ePUB_NAME.epub" ]]; then
-		error "Output file already exists '$ePUB_NAME.epub'"
+	if [[ -f "$EPUB_NAME.epub" ]]; then
+		error "Output file already exists '$EPUB_NAME.epub'"
 	fi
 
-	ePUB_TITLE="${ePUB_TITLE:-$ePUB_NAME}"
+	EPUB_TITLE="${EPUB_TITLE:-$EPUB_NAME}"
 }
 
 # Sort files naturally unless disabled
 #
 # Args: file1, file2, ...
 # Ref: $DO_NOT_SORT_PARAMS
-# Set: $ePUB_FILES
+# Set: $EPUB_FILES
 sort_input_files() {
 	if [[ -n "${DO_NOT_SORT_PARAMS:-}" ]]; then
-		ePUB_FILES=("$@")
+		EPUB_FILES=("$@")
 	else
 		local sorted_files=()
 		while IFS= read -r -d '' file; do
 			sorted_files+=("$file")
 		done < <(printf "%s\0" "$@" | sort -zV)
-		ePUB_FILES=("${sorted_files[@]}")
+		EPUB_FILES=("${sorted_files[@]}")
 	fi
 }
 
 # Extract all ePUB files
 #
-# Ref: $ePUB_FILES(), $TEMP_DIR
+# Ref: $EPUB_FILES(), $TEMP_DIR
 # Set: file
 extract_epubs() {
-	for i in "${!ePUB_FILES[@]}"; do
-		log "Extracting ${ePUB_FILES[i]}"
+	for i in "${!EPUB_FILES[@]}"; do
+		log "Extracting ${EPUB_FILES[i]}"
 		mkdir -p "$TEMP_DIR/$i"
-		unzip -q "${ePUB_FILES[i]}" -d "$TEMP_DIR/$i" \
-			|| error "Failed to extract '${ePUB_FILES[i]}'"
+		unzip -q "${EPUB_FILES[i]}" -d "$TEMP_DIR/$i" \
+			|| error "Failed to extract '${EPUB_FILES[i]}'"
 	done
 }
 
@@ -404,22 +404,22 @@ detect_language() {
 
 # Make paths arrays (OPF_FILES, NCX_FILES) of input ePUBs
 #
-# Ref: $ePUB_FILES, file
+# Ref: $EPUB_FILES, file
 # Set: $FIRST_NCX_ID, $NCX_FILES, $OPF_FILES
 get_opf_ncx_array() {
-	for i in "${!ePUB_FILES[@]}"; do
+	for i in "${!EPUB_FILES[@]}"; do
 		# "$i"/* hides hidden dir in $i
 		cur_opf="$(find "$i" -not -path "*/.*" -name "*.opf" | head -1)"
 
 		[[ -n "$cur_opf" ]] \
-			|| error "No OPF file found in ${ePUB_FILES[i]}"
+			|| error "No OPF file found in ${EPUB_FILES[i]}"
 
 		OPF_FILES[i]="$cur_opf"
 
 		cur_ncx="$(find "$i" -not -path "*/.*" -name "*.ncx" | head -1)"
 
 		[[ -n "$cur_ncx" ]] \
-			|| error "No NCX file found in ${ePUB_FILES[i]}"
+			|| error "No NCX file found in ${EPUB_FILES[i]}"
 
 		NCX_FILES[i]="$cur_ncx"
 	done
@@ -433,11 +433,11 @@ get_opf_ncx_array() {
 
 # Detect volume prefix and suffix based on language
 #
-# Ref: $ePUB_LANG, $TOC_VOLUME_LABELS_GIVEN, $TOC_VOLUME_PREFIX, 
+# Ref: $EPUB_LANG, $TOC_VOLUME_LABELS_GIVEN, $TOC_VOLUME_PREFIX, 
 #      $TOC_VOLUME_SUFFIX
 # Set: $TOC_VOLUME_PREFIX, $TOC_VOLUME_SUFFIX
 detect_volume_labels() {
-	local lang="$ePUB_LANG"
+	local lang="$EPUB_LANG"
 	local prefix="$TOC_VOLUME_PREFIX"
 	local suffix="$TOC_VOLUME_SUFFIX"
 
@@ -515,7 +515,7 @@ find_file() {
 
 # Generate table of contents
 #
-# Ref: $NCX_FILES, $ePUB_FILES, $TOC_VOLUME_PREFIX, $TOC_VOLUME_SUFFIX
+# Ref: $NCX_FILES, $EPUB_FILES, $TOC_VOLUME_PREFIX, $TOC_VOLUME_SUFFIX
 # Set: file
 generate_ncx() {
 	detect_volume_labels
@@ -527,7 +527,7 @@ generate_ncx() {
 	sed '/<navMap>/q' "${NCX_FILES[0]}" > "toc.ncx"
 
 	# Process each volume
-	for i in "${!ePUB_FILES[@]}"; do
+	for i in "${!EPUB_FILES[@]}"; do
 		local cur_ncx cur_ncx_dir volume_num
 
 		cur_ncx="${NCX_FILES[i]}"
@@ -591,7 +591,7 @@ fix_play_order() {
 
 # Generate OPF manifest and spine
 #
-# Ref: $OPF_FILES, $ePUB_FILES, $ePUB_NAME
+# Ref: $OPF_FILES, $EPUB_FILES, $EPUB_NAME
 # Set: file
 generate_opf() {
 	local manifest_file="content.opf.manifest"
@@ -599,7 +599,7 @@ generate_opf() {
 
 	# Initialize OPF with header
 
-	sed -e "s|<dc:title>.*</dc:title>|<dc:title>$ePUB_NAME</dc:title>|" \
+	sed -e "s|<dc:title>.*</dc:title>|<dc:title>$EPUB_NAME</dc:title>|" \
 		-e "s|<meta[^>]*over.*content=[\"'][^\"']*|&-0|" \
 		-e '/<manifest>/q' "${OPF_FILES[0]}" \
 		| grep -v 'calibre:series' \
@@ -607,7 +607,7 @@ generate_opf() {
 		> "content.opf"
 
 	# Process each volume for manifest and spine
-	for i in "${!ePUB_FILES[@]}"; do
+	for i in "${!EPUB_FILES[@]}"; do
 		cur_opf="${OPF_FILES[i]}"
 		cur_opf_dir="$(dirname "$cur_opf")"
 
@@ -669,12 +669,12 @@ encode_nfc(){
 
 # For epub-split, save current OPF and NCX to .epub-merge/
 #
-# Ref: $ePUB_FILES, $OPF_FILES, $NCX_FILES
+# Ref: $EPUB_FILES, $OPF_FILES, $NCX_FILES
 # Set: file
 backup_for_splitting() {
 	mkdir .epub-merge
 
-	for i in "${!ePUB_FILES[@]}"; do
+	for i in "${!EPUB_FILES[@]}"; do
 		local cur_opf="${OPF_FILES[i]}"
 		local cur_opf_dir
 		cur_opf_dir="$(dirname "$cur_opf")"
@@ -716,7 +716,7 @@ backup_for_splitting() {
 				-e "s:\"\./:\":g" "$cur_ncx" \
 			> .epub-merge/"$i".ncx
 
-		basename "${ePUB_FILES[i]}" > .epub-merge/"$i".name
+		basename "${EPUB_FILES[i]}" > .epub-merge/"$i".name
 		encode_nfc .epub-merge/"$i".name
 	done
 }
@@ -841,10 +841,10 @@ finalize_metadata() {
 
 # Create final ePUB file
 #
-# Ref: $ePUB_NAME, $START_DIR
+# Ref: $EPUB_NAME, $START_DIR
 # Set: file
 create_epub() {
-	local output_file="$ePUB_NAME.epub"
+	local output_file="$EPUB_NAME.epub"
 
 	# Package ePUB with proper compression
 	zip -q -0 -X "$output_file" mimetype
@@ -949,7 +949,7 @@ main() {
 		validate_epub "$epub"
 	done
 
-	debug "Sort input files and save them to ePUB_FILES"
+	debug "Sort input files and save them to EPUB_FILES"
 	sort_input_files "$@"
 
 	debug "Generating merged ePUB..."
@@ -972,8 +972,8 @@ main() {
 	setup_base_structure
 
 	debug 'Detect language'
-	ePUB_LANG="$(detect_language "${OPF_FILES[0]}" "$ePUB_LANG")"
-	readonly ePUB_LANG
+	EPUB_LANG="$(detect_language "${OPF_FILES[0]}" "$EPUB_LANG")"
+	readonly EPUB_LANG
 
 	debug 'Generate NCX and OPF'
 	generate_ncx
