Add test cases for cover-related options

diff --git a/epub-meta b/epub-meta
--- a/epub-meta
+++ b/epub-meta
@@ -6,10 +6,10 @@ readonly DEBUG=${DEBUG:-}  # Debug output toggle.
 
 quiet_mode=""              # Suppress non-critical logs.
 edit_mode=""               # If not set, show metadata; if set, modify.
-fix_cover=""               # Fix cover if set
-set_cover=""               # Set new cover if set
-replace_cover=""           # Replace existing cover if set
-extract_cover=""           # Extract cover if set
+fix_cover_given=""         # Fix cover if set
+new_cover_path=""          # Set new cover if set
+alt_cover_path=""          # Replace existing cover if set
+out_cover_path=""          # Extract cover if set
 
 epub_file=""               # Input EPUB file path.
 opf_file=""                # Input OPF file path (if given).
@@ -44,10 +44,10 @@ new_modified=""
 
 # --- Label translations
 
-LANG_IS_KR="$(defaults read -g AppleLanguages 2> /dev/null \
+lang_is_kr="$(defaults read -g AppleLanguages 2> /dev/null \
 	| grep 'ko-' || true)" # Just my preference
 
-if [[ "${LANG:-ko_KR}" == ko* || -n "$LANG_IS_KR" ]]; then
+if [[ "${LANG:-ko_KR}" == ko* || -n "$lang_is_kr" ]]; then
 	readonly label_title="제목"
 	readonly label_author="작가"
 	readonly label_translator="번역"
@@ -172,6 +172,74 @@ check_file_type() {
 	error "$(basename "$1"): not an EPUB or OPF file"
 }
 
+parse_args() {
+	while getopts "t:a:r:p:s:l:d:i:x:c:C:S:u:m:qhf" opt; do
+		# shellcheck disable=SC2034
+		case $opt in
+			t) new_title="${OPTARG:-$removing}"; edit_mode=1 ;;
+			a) new_author="${OPTARG:-$removing}"; edit_mode=1 ;;
+			c) new_cover_path="$(realpath "${OPTARG}")" ;;
+			C) alt_cover_path="$(realpath "${OPTARG}")" ;;
+			f) fix_cover_given=1 ;;
+			S) out_cover_path="$(realpath "$(dirname \
+				"${OPTARG}")")/$(basename "${OPTARG}")" ;;
+			q) quiet_mode=1 ;;
+			r) new_translator="${OPTARG:-$removing}"; edit_mode=1 ;;
+			p) new_publisher="${OPTARG:-$removing}"; edit_mode=1 ;;
+			s) new_subject="${OPTARG:-$removing}"; edit_mode=1 ;;
+			l) new_language="${OPTARG:-$removing}"; edit_mode=1 ;;
+			d) new_description="${OPTARG:-$removing}"
+			   edit_mode=1 ;;
+			i) new_isbn="${OPTARG:-$removing}"; edit_mode=1 ;;
+			x) new_rights="${OPTARG:-$removing}"; edit_mode=1 ;;
+			u) new_published="${OPTARG:-$removing}"; edit_mode=1 ;;
+			m) new_modified="${OPTARG:-$removing}"; edit_mode=1 ;;
+			h) show_usage ;;
+			\?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
+			:) echo "Option -$OPTARG requires an argument." >&2
+			   exit 1 ;;
+		esac
+	done
+
+	readonly new_title new_author new_cover_path alt_cover_path \
+		fix_cover_given out_cover_path quiet_mode new_translator \
+		new_publisher new_subject new_language new_description \
+		edit_mode new_isbn new_rights new_published new_modified
+}
+
+validate_args() {
+	if [[ $# -ne 1 ]]; then
+		show_usage
+	fi
+
+	check_file_type "$1"
+
+	if [[ -n "$epub_file" ]]; then
+		epub_opf="$(unzip -p "$epub_file" META-INF/container.xml \
+			| sed -n "s#.*full-path=.\([^\"']*\).*#\\1#p")"
+
+		if [[ -z "$epub_opf" ]]; then
+			error "OPF file not found."
+		fi
+	fi
+
+	if [[ -z "$epub_file" ]]; then
+		if [[ -n "$fix_cover_given" || -n "$new_cover_path" \
+			|| -n "$out_cover_path" || -n "$alt_cover_path" ]]; then
+		error 'cover-related options cannot be used with OPF file'
+		fi
+	fi
+
+	if [[ ( -n "$new_cover_path" || -n "$alt_cover_path" ) \
+		&& -n "$fix_cover_given" ]]; then
+		error "Option '-f' cannot be used with '-c' or '-C'"
+	fi
+
+	if [[ -n "$new_cover_path" && -n "$alt_cover_path" ]]; then
+		error "Option '-c' and '-C' cannot be used together"
+	fi
+}
+
 # --- XML handling helpers
 
 escape_xml() {
@@ -218,7 +286,7 @@ split_xml_elements() {
 	tr -d '\r' | tr '\n' $real_lf | sed -E "$sed_split_xml_elements"
 }
 
-sed_split_xml_elements=$(cat << 'EOF'
+sed_split_xml_elements="
 s#<dc:(title|publisher|subject|creator|description|rights|language\
 |contributor|date|identifier)([[:blank:]]*|[[:blank:]]+[^>]*)/>\
 #<dc:\1\2></dc:\1>#g;
@@ -229,8 +297,7 @@ s#(</dc:title[^>]*>|</dc:publisher[^>]*>|</dc:subject[^>]*>|</dc:creator[^>]*>\
 
 s#<dc:(title|publisher|subject|creator|description|rights|language\
 |contributor|identifier|date)#\n&#g
-EOF
-)
+"
 readonly sed_split_xml_elements
 
 # --- Metadata edit
@@ -352,16 +419,6 @@ build_all_filters() {
 	color_filter="${color_filter%?}"
 }
 
-make_output() {
-	# Make final output
-	if [[ -z "$opf_file" ]]; then
-		format_opf > "$epub_opf"
-		zip -q -Xr9D "$epub_file" "$(dirname "$epub_opf")"
-	else
-		format_opf > "$opf_file"
-	fi
-}
-
 # --- Start main routine
 
 trap 'printf "\033[31mError ($(basename "$0")): at line '\
@@ -369,62 +426,10 @@ trap 'printf "\033[31mError ($(basename "$0")): at line '\
 
 trap cleanup EXIT
 
-while getopts "t:a:r:p:s:l:d:i:x:c:C:S:u:m:qhC" opt; do
-	# shellcheck disable=SC2034
-	case $opt in
-		t) new_title="${OPTARG:-$removing}"; edit_mode=1 ;;
-		a) new_author="${OPTARG:-$removing}"; edit_mode=1 ;;
-		c) set_cover="$(realpath "${OPTARG}")" ;;
-		C) replace_cover="$(realpath "${OPTARG}")" ;;
-		f) fix_cover=1 ;;
-		S) extract_cover="$(realpath "$(dirname "${OPTARG}")")/$(basename "${OPTARG}")" ;;
-		q) quiet_mode=1 ;;
-		r) new_translator="${OPTARG:-$removing}"; edit_mode=1 ;;
-		p) new_publisher="${OPTARG:-$removing}"; edit_mode=1 ;;
-		s) new_subject="${OPTARG:-$removing}"; edit_mode=1 ;;
-		l) new_language="${OPTARG:-$removing}"; edit_mode=1 ;;
-		d) new_description="${OPTARG:-$removing}"; edit_mode=1 ;;
-		i) new_isbn="${OPTARG:-$removing}"; edit_mode=1 ;;
-		x) new_rights="${OPTARG:-$removing}"; edit_mode=1 ;;
-		u) new_published="${OPTARG:-$removing}"; edit_mode=1 ;;
-		m) new_modified="${OPTARG:-$removing}"; edit_mode=1 ;;
-		h) show_usage ;;
-		\?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
-		:) echo "Option -$OPTARG requires an argument." >&2; exit 1 ;;
-	esac
-done
-
+parse_args "$@"
 shift $((OPTIND-1))
 
-if [[ $# -ne 1 ]]; then
-	show_usage
-fi
-
-check_file_type "$1"
-
-if [[ -n "$epub_file" ]]; then
-	epub_opf="$(unzip -p "$epub_file" META-INF/container.xml \
-		| sed -n "s#.*full-path=.\([^\"']*\).*#\\1#p")"
-
-	if [[ -z "$epub_opf" ]]; then
-		error "OPF file not found."
-	fi
-fi
-
-if [[ -z "$epub_file" ]]; then
-	if [[ -n "$fix_cover" || -n "$set_cover" || -n "$extract_cover" \
-			|| -n "$replace_cover" ]]; then
-		error 'cover-related options cannot be used with OPF file'
-	fi
-fi
-
-if [[ -n "$fix_cover" && ( -n "$set_cover" || -n "$replace_cover" ) ]]; then
-	error "Option '-f' cannot be used with '-c' or '-C'"
-fi
-
-if [[ -n "$set_cover" && -n "$replace_cover" ]]; then
-	error "Option '-c' and '-C' cannot be used together"
-fi
+validate_args "$@"
 
 # --- Read metadata
 
@@ -454,8 +459,7 @@ s#<[^>]*opf:file-as=[\"']([^\"']+)[\"'][^>]*opf:role=[\"']aut[\"'][^>]*[^>]*>\
 ${r_matching}#05${label_author}: \\2 [\\1]#
 s#(<dc:creator[^>]*>)${r_matching}#05${label_author}: \\2#
 p
-}
-"
+}"
 
 show_tags() {
 	# Parse OPF XML and output readable metadata (title, author, etc.)
@@ -466,8 +470,8 @@ show_tags() {
 		| unescape_xml
 }
 
-if [[ -z "$edit_mode" && -z "$fix_cover" && -z "$extract_cover" \
-		&& -z "$set_cover" && -z "$replace_cover" ]]; then
+if [[ -z "$edit_mode" && -z "$fix_cover_given" && -z "$out_cover_path" \
+		&& -z "$new_cover_path" && -z "$alt_cover_path" ]]; then
 	# No edit option, then read metadata and exit.
 	if [[ -z "$opf_file" ]]; then
 		unzip -p "$epub_file" "$epub_opf"
@@ -548,14 +552,14 @@ else
 	format_opf > "$opf_file"
 fi
 
-if [[ -z "$fix_cover" && -z "$extract_cover" && -z "$set_cover" \
-		&& -z "$replace_cover" ]]; then
+if [[ -z "$fix_cover_given" && -z "$out_cover_path" && -z "$new_cover_path" \
+		&& -z "$alt_cover_path" ]]; then
 	debug "exit after second show_tags"
 	exit
 fi
 
-# --- Handle cover
-
+# --- Functions for handling covers
+#
 if [[ "$OSTYPE" == "darwin"* ]]; then
 	sed_i() {
 		sed -i '' "$@"
@@ -564,15 +568,6 @@ else
 	sed_i() {
 		sed -i "$@"
 	}
-fi
-
-epub_version="$(grep -om1 'package[^>]*version="[0-9.]*"' "$opf_header" \
-	| grep -om1 'version=.[0-9.]*.' | cut -d'"' -f2)"
-readonly epub_version
-
-cover_meta_found=""
-if grep -qom1 "<meta[^>]*name=.cover[\"'][^>]*>" "$epub_opf"; then
-	cover_meta_found=1
 fi
 
 get_media_type() {
@@ -589,11 +584,13 @@ get_media_type() {
 }
 
 change_cover_id() {
+	# Add cover meta: <meta content="cover-id" name="cover"/>
+	# Add properties="cover-image" to cover-id manifest item
 	local id="$1"
-	local sed_cover_meta_replace="s|<meta[^>]*name=[\"\x27]cover"\
-"[\"\x27][^>]*>|<meta content=\"$id\" name=\"cover\"/>|"
-	local echo_cover_meta="${indent}${indent}<meta content=\"$id\" "\
-"name=\"cover\"/>${real_lf}"
+	local sed_cover_meta_replace="s|<meta[^>]*name=[\"\x27]cover[\"\x27]"
+	sed_cover_meta_replace+="[^>]*>|<meta content=\"$id\" name=\"cover\"/>|"
+	local echo_cover_meta="${indent}${indent}<meta content=\"$id\" "
+	echo_cover_meta+="name=\"cover\"/>${real_lf}"
 
 	debug "change cover id"
 	if [[ -n "$cover_meta_found" ]]; then
@@ -603,12 +600,14 @@ change_cover_id() {
 		cover_meta_found=1
 	fi
 
+	local sed_cover_properties_add="s#<item.*id=[\"']$id[\"']#& "
+	sed_cover_properties_add+="properties=\"cover-image\"#"
 	if [[ "$epub_version" != "2.0" ]]; then
 		debug "set ePUB3 cover-image properties: $id"
 		sed -E -e 's/properties="cover-image"//g' \
-			-e "s#<ite.*id=[\"']$id[\"']#& properties=\"cover-image\"#" \
-			"$opf_footer" \
-			> "$opf_footer".new && mv -f "$opf_footer".new "$opf_footer"
+			-e "$sed_cover_properties_add" "$opf_footer" \
+			> "$opf_footer".new \
+			&& mv -f "$opf_footer".new "$opf_footer"
 	fi
 }
 
@@ -628,9 +627,8 @@ find_cover_id_of_html() {
 
 	# Extract first image filename from HTML (e.g., "cover.jpg")
 	local img_filename
-	img_filename=$(grep -o \
-			'<img[^>]*src=["'"'"'][^"'"'"']*["'"'"']' "$html_path" \
-		| head -n1 \
+	img_filename=$(grep -om1 '<img[^>]*src=["'"'"'][^"'"'"']*["'"'"']' \
+			"$html_path" \
 		| sed -E 's/.*src=["'"'"']([^"'"'"']*)["'"'"'].*/\1/' \
 		| xargs basename)
 
@@ -651,7 +649,46 @@ find_cover_id_of_html() {
 	echo -e "${id}\t${href}"
 }
 
-readonly cover_opf="$epub_opf.cover"
+# --- Handle covers
+
+# --- Process '-c' option
+
+epub_version="$(grep -om1 'package[^>]*version="[0-9.]*"' "$opf_header" \
+	| grep -om1 'version=.[0-9.]*.' | cut -d'"' -f2)"
+readonly epub_version
+
+cover_meta_found=""
+if grep -qom1 "<meta[^>]*name=.cover[\"'][^>]*>" "$epub_opf"; then
+	cover_meta_found=1
+fi
+
+if [[ -n "$new_cover_path" ]]; then
+	new_id="cover-$(date +%s)"
+	new_ext="$(echo "${new_cover_path##*.}" | tr '[:upper:]' '[:lower:]')"
+	epub_cover_path="$(dirname "$epub_opf")/$new_id.$new_ext"
+	new_type="$(get_media_type "cover.$new_ext")"
+	cp "$new_cover_path" "$epub_cover_path"
+
+	item="<item href=\"$new_id.$new_ext\" id=\"$new_id\" "
+	item+="media-type=\"$new_type\"/>"
+	sed_i "s#<manifest[^>]*>#&$real_lf$indent$indent$item#" "$opf_footer"
+
+	change_cover_id "$new_id"
+
+	format_opf > "$epub_opf"
+	zip -q -Xr9D "$epub_file" "$epub_cover_path" "$epub_opf"
+
+	log "Successfully set new image as cover: $epub_cover_path"
+
+	if [[ -z "$fix_cover_given" && -z "$out_cover_path" \
+			&& -z "$alt_cover_path" ]]; then
+		exit
+	fi
+fi
+
+# --- Functions and variables for '-C', '-f', and '-S' options
+
+readonly cover_opf="$epub_opf.cover"  # Need to be same dir to $epub_opf
 sed 's/</\n</g' "$epub_opf" > "$cover_opf"
 
 id_href="$(awk '
@@ -659,7 +696,8 @@ id_href="$(awk '
 	# Args: line - the XML line to parse, attr - attribute name to extract
 	# Returns: attribute value or empty string if not found
 	function extract_attr(line, attr) {
-		regex = attr "[[:space:]]*=[[:space:]]*[\"'\''][^\"'\'']*[\"'\'']"
+		regex = attr \
+			"[[:space:]]*=[[:space:]]*[\"'\''][^\"'\'']*[\"'\'']"
 		if (match(tolower(line), tolower(regex))) {
 			val = substr(line, RSTART, RLENGTH)
 			# Remove attribute name and quotes
@@ -726,14 +764,16 @@ id_href="$(awk '
 				# Store candidate if id or href contains "cover"
 				id_lower = tolower(id)
 				href_lower = tolower(href)
-				if ((id_lower ~ /cover/ || href_lower ~ /cover/) \
+				if ((id_lower ~ /cover/ \
+						|| href_lower ~ /cover/) \
 						&& candidate_href == "") {
 					candidate_id = id
 					candidate_href = href
 				}
 				
 				# Match with meta cover id (EPUB 2 standard)
-				if (meta_cover_id != "" && id == meta_cover_id) {
+				if (meta_cover_id != "" \
+						&& id == meta_cover_id) {
 					print id "\t" href
 					cover_found = 1
 					exit
@@ -746,7 +786,7 @@ id_href="$(awk '
 			}
 		}
 		
-		# 3. Search for <reference type="cover" href="..."> in guide section
+		# 3. Search for <reference type="cover" href="..."> in guide
 		if (guide_href == "" && line_lower ~ reference_pattern) {
 			h = extract_attr(line, "href")
 			if (h != "") {
@@ -794,25 +834,6 @@ fi
 
 rm -f "$cover_opf"
 
-if [[ -n "$set_cover" ]]; then
-	new_id="cover-$(date +%s)"
-	new_ext="$(echo "${set_cover##*.}" | tr '[:upper:]' '[:lower:]')"
-	new_cover_path="$(dirname "$epub_opf")/$new_id.$new_ext"
-	new_type="$(get_media_type "cover.$new_ext")"
-	cp "$set_cover" "$new_cover_path"
-
-	item="<item href=\"$new_id.$new_ext\" id=\"$new_id\" "
-	item+="media-type=\"$new_type\"/>"
-	sed_i "s#<manifest[^>]*>#&$real_lf$indent$indent$item#" "$opf_footer"
-
-	change_cover_id "$new_id"
-
-	format_opf > "$epub_opf"
-	zip -q -Xr9D "$epub_file" "$new_cover_path" "$epub_opf"
-
-	log "New cover successfully set: $set_cover"
-fi
-
 id="${id_href%%$'\t'*}"
 href="${id_href#*$'\t'}"
 
@@ -820,31 +841,33 @@ if [[ -z "$id" || -z "$href" ]]; then
 	error "$(basename "$1"): failed to find cover id"
 fi
 
-if [[ -n "$replace_cover" ]]; then
+if [[ -n "$alt_cover_path" ]]; then
 	image_path="$(dirname "$epub_opf")/$href"
 	mkdir -p "$(dirname "$image_path")"
-	cp "$replace_cover" "$image_path"
+	cp "$alt_cover_path" "$image_path"
 
 	change_cover_id "$id"
 
 	format_opf > "$epub_opf"
 	zip -q -Xr9D "$epub_file" "$epub_opf" "$image_path"
 
-	log "Cover image ($href) replaced with \"$replace_cover\""
+	log "Replaced cover image ($href) with \"$alt_cover_path\""
 fi
 
-if [[ -n "$fix_cover" ]]; then
+if [[ -n "$fix_cover_given" ]]; then
 	change_cover_id "$id"
 	format_opf > "$epub_opf"
 	zip -q -Xr9D "$epub_file" "$epub_opf"
 
-	log "New cover successfully set: $href [$id]"
+	log "Successfully set internal image as cover: $href [$id]"
 fi
 
-if [[ -n "$extract_cover" ]]; then
+if [[ -n "$out_cover_path" ]]; then
 	image_path="$(dirname "$epub_opf")/$href"
-	unzip -q "$epub_file" "$image_path"
+	image_path="$(echo "$image_path" | sed 's#^\./##')"
 	new_ext="$(echo "${image_path##*.}" | tr '[:upper:]' '[:lower:]')"
-	cp -i "$image_path" "$extract_cover.$new_ext" \
-		&& log "Cover image ($href) copied to \"$extract_cover.$new_ext\""
+
+	unzip -q "$epub_file" "$image_path"
+	cp -i "$image_path" "$out_cover_path.$new_ext" && \
+		log "Copied cover image ($href) to \"$out_cover_path.$new_ext\""
 fi
